### ISSUE TITLE
Retry-After header should be in <seconds> while setTimeout accepts <milliseconds>

### ISSUE THREAD

**Issue by mihai-stancu** [compwright/axios-retry-after#4]
[Here](https://github.com/compwright/axios-retry-after/blob/master/src/utils.js#L14) the code takes the exact value of a `retry-after` header and passes it unchanged to `setTimeout`.

Since documentation says `retry-after` header should be expressed in `seconds` (or an exact date), and `setTimeout` accepts its delay in `milliseconds` this incompatibility forces the backend server to respond with a `retry-after` header in the thousands of seconds range to compensate.

**Comment by vboufleur** [comment]
+1 on this. Also, the Retry-After header can have a Date to retry the request, instead of the number of seconds: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

It would be great if this module was smart enough to 1) transform the number of seconds to milliseconds for setTimeout, and 2) detect if the header contains a Date and configure setTimeout to wait until that date.

**Comment by vboufleur** [comment]
@compwright

**Comment by compwright** [comment]
@vboufleur I would welcome a pull request if you would like to submit one, perhaps based on https://github.com/ItsMeRomian/axios-retry-after/commit/0aaa7fbadeda900c832f54d0977953fb7c672bc2. If not, I will get to it when I have time between taking care of paying clients.

**Comment by vboufleur** [comment]
@compwright I've made the PR with the changes we talked about in this thread. Here it is: https://github.com/compwright/axios-retry-after/pull/9
